kpu:
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: lmx
    password: lmx
  druid:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'ZHadmin123.'
    url: jdbc:mysql://127.0.0.1:3218/kpu_boot_column?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
  database:
    isNotWrite: true
  file:
    storageType: MIN_IO
    delFile: false
    minIo:
      endpoint: "https://static.lmx.top/"
      accessKey: "kpu"
      secretKey: "."
      bucket: "dev"
  swagger:
    # 正式环境用nginx代理，为了保持和cloud版本一致的URL，特意调整
    docket:
      general:
        base-path: /api/oauth
      oauth:
        base-path: /api/oauth
      auth:
        base-path: /api/authority
      common:
        base-path: /api/authority
      core:
        base-path: /api/authority
      tenant:
        base-path: /api/tenant
      msg:
        base-path: /api/msg
      file:
        base-path: /api/file
      activiti:
        base-path: /api/activiti
