kpu:
  redis:
    ip: 47.114.137.78
    port: 6379
    password: lmx123125
    database: 7
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: lmx
    password: lmx
  database:
    isNotWrite: true
  file:
    storageType: MIN_IO
    delFile: false
    minIo:
      endpoint: "https://static.lmx.top/"
      accessKey: "kpu"
      secretKey: "."
      bucket: "dev"
