kpu:
  system:
    # 登录时否验证密码有效性 （常用于开发环境快速登录）
    verifyPassword: true
    # 登录时否验证验证码有效性 （常用于开发环境快速登录）
    verifyCaptcha: true
  cache:
    type: REDIS
  redis:
    ip: 127.0.0.1
    port: 16379
    password: SbtyMveYNfLzTks7H0apCmyStPzWJqjy
    database: 0
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: kpu
    password: kpu
  druid:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'root'
    url: jdbc:mysql://127.0.0.1:3306/kpu_defaults?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
  database:
    dbType: MYSQL
    # 需要初始化的数据库前缀
    initDatabasePrefix:
      - kpu_base
    # SCHEMA模式专用 当前服务的租户库前缀
    tenantDatabasePrefix: kpu_base
    # SCHEMA模式专用
    owner: ''
    multiTenantType: NONE
    # COLUMN模式专用 隔离租户的字段
    tenantIdColumn: tenant_code
    isNotWrite: false
    isBlockAttack: false  # 是否启用 攻击 SQL 阻断解析器
    isSeata: false
    p6spy: true
    id-type: HU_TOOL
    hutoolId:
      workerId: 0
      dataCenterId: 0
    cache-id:
      time-bits: 31
      worker-bits: 22
      seq-bits: 10
      epochStr: '2020-09-15'
      boost-power: 3
      padding-factor: 50
  echo:
    # 是否启用 远程数据 手动注入
    enabled: true
    # 是否启用 远程数据 注解注入
    aop-enabled: true
  authentication:
    expire: 28800               # token有效期为8小时
    refreshExpire: 86400        # 刷新token有效期为24小时
  security:
    # 是否开启URI权限校验
    enabled: false
    type: SERVICE
    caseSensitive: false
  log:
    enabled: true
    type: DB
  xss:
    enabled: true
    requestBodyEnabled: false
  file:
    storageType: LOCAL #  FAST_DFS LOCAL MIN_IO ALI_OSS HUAWEI_OSS QINIU_OSS
    delFile: false
    local:
      storage-path: /Users/lmx/Documents/kpu/uploadfile/file/     # 文件存储路径  （ 某些版本的 window 需要改成  D:\\data\\projects\\uploadfile\\file\\  ）
      endpoint: http://127.0.0.1/file/   # 文件访问 （部署nginx后，配置nginx的ip，并配置nginx静态代理storage-path地址的静态资源）
      inner-uri-prefix: null  #  内网的url前缀
    ali:
      # 请填写自己的阿里云存储配置
      uriPrefix: "http://lmx-admin-cloud.oss-cn-beijing.aliyuncs.com/"
      bucket-name: "lmx-admin-cloud"
      endpoint: "oss-cn-beijing.aliyuncs.com"
      access-key-id: "填写你的id"
      access-key-secret: "填写你的秘钥"
    minIo:
      endpoint: "http://127.0.0.1:9000/"
      accessKey: "kpu"
      secretKey: "kpu"
      bucket: "dev"
    huawei:
      uriPrefix: "dev.obs.cn-southwest-2.myhuaweicloud.com"
      endpoint: "obs.cn-southwest-2.myhuaweicloud.com"
      accessKey: "1"
      secretKey: "2"
      location: "cn-southwest-2"
      bucket: "dev"
    qiNiu:
      zone: "z0"
      accessKey: "1"
      secretKey: "2"
      bucket: "lmx_admin_cloud"
  swagger:
    license: Powered By lmx
    licenseUrl: https://github.com/lmx
    termsOfServiceUrl: https://github.com/lmx
    version: '@project.version@'
    global-operation-parameters:
      - name: token
        description: 用户身份token
        modelRef: String
        parameterType: header
        required: true
        # 默认值只是方便本地开发时，少填参数，生产环境请禁用swagger或者禁用默认参数
        defaultValue: "Bearer test"
      - name: Authorization
        description: 客户端信息
        modelRef: String
        parameterType: header
        required: true
        defaultValue: "Basic a3B1X3dlYjprcHVfd2ViX3NlY3JldA=="
      - name: tenant
        description: 租户编码
        modelRef: String
        parameterType: header
        required: false
        defaultValue: "MDAwMA=="
    docket:
      oauth:
        title: 认证模块
        base-package: cn.lmx.kpu.oauth.controller
      auth:
        title: 权限模块
        base-package: cn.lmx.kpu.authority.controller.auth
      common:
        title: 公共模块
        base-package: cn.lmx.kpu.authority.controller.common
      core:
        title: 组织模块
        base-package: cn.lmx.kpu.authority.controller.core
      tenant:
        title: 租户模块
        base-package: cn.lmx.kpu.tenant.controller
      msg:
        title: 消息服务
        base-package: cn.lmx.kpu.msg.controller;cn.lmx.kpu.sms.controller
      generator:
        title: 代码生成器服务
        base-package: cn.lmx.kpu.generator.controller
      file:
        title: 文件服务
        base-package: cn.lmx.kpu.file.controller
      activiti:
        title: 流程组件模块
        base-package: cn.lmx.kpu.activiti.controller
  captcha:
    type: ARITHMETIC
    width: 158
    height: 58
    len: 2
    charType: 2
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
    keepAliveSeconds: 300
    threadNamePrefix: 'kpu-async-executor-'

  # 代码生成
  generator:
    # 后端代码生成路径
    outputDir: /Users/lmx/Documents/IdeaProjects/kpu
    # 前端代码生成路径
    frontOutputDir: /Users/lmx/Documents/IdeaProjects/kpu
    # 作者
    author: zuihou
    # 表名转换为实体类类名时，是否去除表名前缀
    tablePrefix:
      - xxx_
    # 字段名转换为实体类字段名时，是否去除字段前缀
    fieldPrefix:
      - xxx_
    # 字段名转换为实体类字段名时，是否去除字段后缀
    fieldSuffix:
      - xxx_
    # 项目前缀。 若你的项目改成了 alibaba-base-server，这里就填alibaba
    projectPrefix: 'lamp'
    # 父类
    superClass: SUPER_CLASS
    packageInfoConfig: # 其他配置建议保持PackageInfoConfig中的默认值
      # 生成代码位于 src/main/java 下的基础包
      parent: 'cn.lmx.lamp'
      # lamp-util 项目的基础包
      utilParent: 'cn.lmx.basic'
      # 枚举 位于 src/main/java/{parent}/{moduleName} 下的 包名
      enumeration: 'enumeration'
      # saveVO 位于 src/main/java/{parent}/{moduleName} 下的 包名
      saveVo: 'vo.save'
      # updateVO 位于 src/main/java/{parent}/{moduleName} 下的 包名
      updateVo: 'vo.update'
      # query 位于 src/main/java/{parent}/{moduleName} 下的 包名
      pageQuery: 'vo.query'
      # resultVo src/main/java/{parent}/{moduleName} 下的 包名
      resultVo: 'vo.result'
      # 实体 位于 src/main/java/{parent}/{moduleName} 下的 包名
      entity: 'entity'
      # manager 位于 src/main/java/{parent}/{moduleName} 下的 包名
      manager: 'manager'
      # managerImpl 位于 src/main/java/{parent}/{moduleName} 下的 包名
      managerImpl: 'manager.{}impl'
      # service 位于 src/main/java/{parent}/{moduleName} 下的 包名
      service: 'service'
      # serviceImpl 位于 src/main/java/{parent}/{moduleName} 下的 包名
      serviceImpl: 'service.{}impl'
      # controller 位于 src/main/java/{parent}/{moduleName} 下的 包名
      controller: 'controller'
      # mapper 位于 src/main/java/{parent}/{moduleName} 下的 包名
      mapper: 'mapper'
      # Mapper XML 位于 src/main/resource 下的 包名
      xml: 'mapper_{}/base'
    entity-config: # 实体类配置
      # 【实体、VO】时间类型对应策略  ONLY_DATE: java.util  SQL_PACK:java.sql  TIME_PACK: java.time
      dateType: TIME_PACK
      # 【实体】Entity类的父类
      entitySuperClass: ENTITY
      # 【实体】指定生成的主键的ID类型 (${superClass} == NONE 时，新生成的实体才生效)
      idType: INPUT
      # 【实体、VO】表字段转换为实体字段的命名策略
      columnNaming: underline_to_camel
      # 【实体、VO】生成实体类时，忽略的字段（字段名）
      ignoreColumns:
        - xxx
      # 【实体】 是否生成字段常量
      columnConstant: false
      # 【实体、VO】是否为链式模型
      chain: true
      # 【实体、VO】 是否为lombok模型
      lombok: true
      # 【实体】乐观锁字段名称
      versionColumnName: ''
      # 【实体】乐观锁属性名称
      versionPropertyName: ''
      # 【实体】逻辑删除字段名称
      logicDeleteColumnName: ''
      # 【实体】逻辑删除属性名称
      logicDeletePropertyName: ''
      # 【实体】生成的@TableField注解上需要填充的字段和填充类型
      fillColumnName:
        - xxx: INSERT
      # 【VO】格式化SaveVO文件名称
      formatSaveVoFileName: ''
      # 【VO】格式化UpdateVO文件名称
      formatUpdateVoFileName: ''
      # 【VO】格式化ResultVO文件名称
      formatResultVoFileName: ''
      # 【VO】格式化 PageQuery 文件名称
      formatPageQueryFileName: ''
    mapperConfig: # mapper类配置
      # 格式化Mapper文件名称
      formatMapperFileName: ''
      # 格式化Xml文件名称
      formatXmlFileName: ''
      # 是否添加 @Mapper 注解（默认 false）
      mapperAnnotation: false
      # mapper类上是否添加忽略表结构 @InterceptorIgnore
      columnAnnotationTablePrefix:
        - 表的前缀
      # 生成的xml中，是否包含BaseResultMap（默认 false）
      baseResultMap: true
    serviceConfig:
      # 继承的Service类全称，带包名
      superServiceClass: cn.lmx.basic.base.service.SuperService
      # 继承的ServiceImpl类全称，带包名
      superServiceImplClass: cn.lmx.basic.base.service.impl.SuperServiceImpl
      # 格式化service接口文件名称
      formatServiceFileName: '{}Service'
      # 格式化service实现类文件名称
      formatServiceImplFileName: ''
      # 匹配到此前缀的表，生成的 serviceImpl 类上会自动添加切换数据源注解 @DS
      dsTablePrefix:
        - xxx
    managerConfig:
      # 继承的Manager类全称，带包名
      superManagerClass: 'cn.lmx.basic.base.manager.SuperManager'
      # 继承的ManagerImpl类全称，带包名
      superManagerImplClass: 'cn.lmx.basic.base.manager.impl.SuperManagerImpl'
      # 格式化Manager接口文件名称
      formatManagerFileName: ''
      # 格式化Manager实现类文件名称
      formatManagerImplFileName: ''
    controllerConfig:
      # 生成 @RestController 控制器（默认 false）
      restStyle: true
      # 格式化文件名称
      formatFileName: ''
      # 驼峰转连字符
      hyphenStyle: false
      # 继承的Controller类全称，带包名
      superClass: 'cn.lmx.basic.base.controller.SuperController'
    #    webProConfig:
    #      # 格式化菜单文件名称
    #      formatMenuName: {}维护
    #      # 前端生成页面样式模板
    #      tpl: SIMPLE
    fileOverrideStrategy: # 文件覆盖策略
      entityFileOverride: OVERRIDE
      sqlFileOverride: OVERRIDE
      mapperFileOverride: EXIST_IGNORE
      xmlFileOverride: OVERRIDE
      managerFileOverride: EXIST_IGNORE
      serviceFileOverride: EXIST_IGNORE
      controllerFileOverride: EXIST_IGNORE
      apiModelFileOverride: OVERRIDE
      langFileOverride: OVERRIDE
      indexEditTreeFileOverride: EXIST_IGNORE
      dataFileOverride: EXIST_IGNORE
    constantsPackage: # 公共枚举的完整类名，配置后自定义的枚举类才能正常 import
      # 业务服务 后台手动改动过的枚举
      FieldFill: com.baomidou.mybatisplus.annotation.FieldFill
      SuperClassEnum: cn.lmx.lamp.generator.enumeration.SuperClassEnum
      EntitySuperClassEnum: cn.lmx.lamp.generator.enumeration.EntitySuperClassEnum
      # common 常量
      EchoDictType: cn.lmx.lamp.model.constant.EchoDictType
      EchoApi: cn.lmx.lamp.model.constant.EchoApi
      # common 公共枚举
      HttpMethod: cn.lmx.lamp.model.enumeration.HttpMethod
      BooleanEnum: cn.lmx.lamp.model.enumeration.BooleanEnum
      StateEnum: cn.lmx.lamp.model.enumeration.StateEnum
      UserStatusEnum: cn.lmx.lamp.model.enumeration.base.UserStatusEnum
      RoleCategoryEnum: cn.lmx.lamp.model.enumeration.base.RoleCategoryEnum
      ActiveStatusEnum: cn.lmx.lamp.model.enumeration.base.ActiveStatusEnum
      OrgTypeEnum: cn.lmx.lamp.model.enumeration.base.OrgTypeEnum
      FileType: cn.lmx.lamp.model.enumeration.base.FileType
      DateType: cn.lmx.lamp.model.enumeration.base.DateType
      DictClassifyEnum: cn.lmx.lamp.model.enumeration.system.DictClassifyEnum
      DefTenantStatusEnum: cn.lmx.lamp.model.enumeration.system.DefTenantStatusEnum
      DataTypeEnum: cn.lmx.lamp.model.enumeration.system.DataTypeEnum
      TenantConnectTypeEnum: cn.lmx.lamp.model.enumeration.system.TenantConnectTypeEnum


knife4j:
  enable: true
  setting:
    enableReloadCacheParameter: true
    enableVersion: true
    enableDynamicParameter: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  2020 [kpu-cloud](https://github.com/lmx)

setting:
  path:
    uploadPath: /data/projects/uploadfile/temp/


server:
  shutdown: GRACEFUL
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  port: 8760
  undertow:
    threads:
      io: 8 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      worker: 120  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 2048  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理 , 每块buffer的空间大小,越小的空间被利用越充分
    direct-buffers: true  # 是否分配的直接内存

dozer:
  mappingFiles:
    - classpath*:dozer/*.dozer.xml

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: '@project.artifactId@'
  profiles:
    active: devmysql
  mvc:
    pathmatch:
      # 升级springboot2.6.6后临时处理，防止swagger报错
      matching-strategy: ANT_PATH_MATCHER
  lifecycle:
    # 优雅停机宽限期时间
    timeout-per-shutdown-phase: 30s
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  servlet:
    multipart:
      max-file-size: 512MB      # Max file size，默认1M
      max-request-size: 512MB   # Max request size，默认10M
  rabbitmq:
    enabled: ${kpu.rabbitmq.enabled}
    host: ${kpu.rabbitmq.ip}
    port: ${kpu.rabbitmq.port}
    username: ${kpu.rabbitmq.username}
    password: ${kpu.rabbitmq.password}
    listener:
      type: direct # simple direct
  redis:
    host: ${kpu.redis.ip}
    password: ${kpu.redis.password}
    port: ${kpu.redis.port}
    database: ${kpu.redis.database}
    lettuce:
      pool:
        max-idle: 10
        min-idle: 10
        max-active: 100
  cache:
    type: GENERIC
  datasource:
    # 从这里开始(dynamic)，中间的这段配置用于 kpu.database.multiTenantType == DATASOURCE 时
      # 联系作者开通
    # 从这里结束(dynamic)，中间的这段配置用于 kpu.database.multiTenantType == DATASOURCE 时
    druid:
      enable: true
      # 从这里开始(druid)，中间的这段配置用于 kpu.database.multiTenantType != DATASOURCE 时
      username: ${kpu.druid.username}
      password: ${kpu.druid.password}
      driverClassName: ${kpu.druid.driverClassName}
      url: ${kpu.druid.url}
      db-type: mysql
      validation-query: SELECT 'x'
      initialSize: 10
      minIdle: 10
      maxActive: 200
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
      filters: stat,wall
      filter:
        wall:
          enabled: true
          config:
            strictSyntaxCheck: false
            commentAllow: true
            multiStatementAllow: true
            noneBaseStatementAllow: true
        slf4j:
          enabled: false     # 使用slf4j打印可执行日志时，改成true
          statement-executable-sql-log-enable: true
      # 从这里结束(druid)，中间的这段配置用于 kpu.database.multiTenantType != DATASOURCE 时

      # 以下的2段配置，同时适用于所有模式
      web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true    #允许清空统计数据
        login-username: kpu
        login-password: kpu

mybatis-plus:
  mapper-locations:
    - classpath*:mapper_**/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.lmx.kpu.*.entity;cn.lmx.basic.database.mybatis.typehandler
  typeEnumsPackage: cn.lmx.kpu.*.enumeration
  global-config:
    db-config:
      id-type: INPUT
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      where-strategy: NOT_EMPTY
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    default-enum-type-handler: cn.lmx.basic.database.mybatis.handlers.MybatisEnumTypeHandler

# 用于/actuator/info
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  spring-boot-version: '@spring.boot.version@'

logging:
  file:
    path: /Users/lmx/Documents/IdeaProjects/kpu-boot/logs
    name: ${logging.file.path}/${spring.application.name}/root.log
  config: classpath:logback-spring.xml
  level:
    druid.sql.Statement: debug
