kpu:
  druid-oracle: &druid-oracle
    validation-query: SELECT 'x' FROM DUAL
  druid-mysql: &druid-mysql
    validation-query: SELECT 'x'
  druid-sqlserver: &druid-sqlserver
    validation-query: SELECT 'x'
  mysql: &db-mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: 'LMX123125'
    url: jdbc:mysql://47.114.137.78:3306/kpu?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&useSSL=false

  redis:
    ip: 47.114.137.78
    port: 6379
    password: lmx123125
    database: 9
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: lmx
    password: lmx
  database:
    isNotWrite: true
  file:
    storageType: MIN_IO
    delFile: false
    minIo:
      endpoint: "http://47.114.137.78:9000/"
      accessKey: "root"
      secretKey: "lmx123125"
      bucket: "kpu"
spring:
  datasource:
    dynamic:
      datasource:
        "0": # 只配置了默认数据库  kpu_defaults
          <<: *db-mysql
      druid:
        <<: *druid-mysql